workflows:
  android-release-build:
    name: Android Release Build
    environment:
      java: 17
    scripts:
      - name: Give gradlew permission
        script: chmod +x gradlew

      - name: Build release APK
        script: ./gradlew clean assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "your.email@example.com"
