workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - name: Clean & Build
        script: |
          ./gradlew clean :app:assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - you@example.com
