workflows:
  android-simple-build:
    name: Android Simple Build
    scripts:
      - name: Build unsigned APK
        script: |
          ./gradlew clean assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
