workflows:
  android-simple-build:
    name: Android Simple Build
    instance_type: linux_x2
    environment:
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
    scripts:
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
      - name: Build unsigned APK
        script: |
          ./gradlew clean assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
