workflows:
  android_release:
    name: Android Release (Compose)
    max_build_duration: 60
    environment:
      java: 17
      android:
        sdk: 34
      groups:
        - keystore_credentials
      vars:
        KEYSTORE_PATH: yarhooshmand.keystore
    scripts:
      - name: Clean
        script: ./gradlew clean
      - name: Decode Keystore
        script: |
          echo $RELEASE_KEYSTORE | base64 --decode > yarhooshmand.keystore
      - name: Assemble Release
        script: ./gradlew :app:assembleRelease --stacktrace
    artifacts:
      - app/build/outputs/**/**/*.apk
      - app/build/outputs/**/**/*.aab
