workflows:
  android-simple-build:
    name: Android Simple Build
    environment:
      java: 17
    scripts:
      - name: Give gradlew permission
        script: chmod +x gradlew

      - name: Build unsigned APK
        script: ./gradlew clean assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
