workflows:
  android_release:
    name: Android Release
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_VERSION: 34
      java: 17
      flutter: stable
      xcode: latest
      groups:
        - keystore_credentials
    scripts:
      - name: Get dependencies
        script: ./gradlew dependencies
      - name: Build release
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your@email.com
