name: build-android-apk

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unzip zip libffi-dev libssl-dev build-essential \
            liblzma-dev zlib1g-dev libjpeg-dev libfreetype6-dev \
            libsqlite3-dev libncurses5 libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev libgstreamer1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev
          python -m pip install --upgrade pip wheel setuptools

      - name: Install buildozer
        run: |
          pip install "Cython<3" virtualenv
          pip install buildozer==1.5.0
          buildozer --version

      - name: Build debug APK
        run: |
          # جلوگیری از تعامل
          export BUILDOZER_WARN_ON_ROOT=0
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: YarHooshmand-debug-apk
          path: bin/*.apk
          if-no-files-found: error
