name: Build APK with Buildozer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-11-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer init || true
        buildozer -v android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Android-APK
        path: bin/*.apk
