name: Build Signed APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            ~/Android
          key: android-sdk-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git zip unzip openjdk-17-jdk

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build Release APK
        run: |
          buildozer android release

      # بازگردانی Keystore از Secrets
      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_FILE" | base64 --decode > my-release-key.keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      # امضای APK
      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore my-release-key.keystore \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          bin/*.apk ${{ secrets.KEY_ALIAS }}

      # تراز کردن APK
      - name: Align APK
        run: |
          zipalign -v 4 bin/*.apk app-release.apk

      # خروجی نهایی
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: app-release.apk
