name: Android CI Stable

on:
  workflow_dispatch:
    inputs:
      module:
        description: "مسیر ماژول (مثال: :app)"
        required: true
        default: ":app"
      buildType:
        description: "نوع بیلد (Debug یا Release)"
        required: true
        default: "Debug"
      gradleArgs:
        description: "آرگومان‌های اضافی گرادل (اختیاری)"
        required: false
        default: ""
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      MODULE: ${{ github.event.inputs.module || ':app' }}
      BUILD_TYPE: ${{ github.event.inputs.buildType || 'Debug' }}
      GRADLE_ARGS: ${{ github.event.inputs.gradleArgs || '' }}
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_DISTRIBUTION: temurin
      ANDROID_NDK_VERSION: 25.2.9519653
      CMAKE_VERSION: 3.22.1
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up Java 17 (primary)
        id: jdk17
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: "17"
          cache: gradle

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install Android packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" \
            "platforms;android-33" "build-tools;33.0.2" \
            "platforms;android-34" "build-tools;34.0.0" \
            "platforms;android-35" "build-tools;35.0.0" \
            "ndk;${ANDROID_NDK_VERSION}" "cmake;${CMAKE_VERSION}"

      - name: Configure Gradle for CI
        run: |
          mkdir -p ~/.gradle
          cat >> ~/.gradle/gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
          org.gradle.daemon=false
          android.useAndroidX=true
          android.enableJetifier=true
          kotlin.incremental=false
          EOF

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Warm dependencies
        run: ./gradlew --no-daemon --stacktrace --info help

      - name: Build on Java 17 (attempt 1)
        id: build_j17
        continue-on-error: true
        run: |
          ./gradlew clean $MODULE:assemble$BUILD_TYPE \
            -x lint -x lintVitalRelease -x test \
            --no-daemon --stacktrace --info --warning-mode all $GRADLE_ARGS

      - name: Set up Java 11 (fallback)
        if: ${{ steps.build_j17.outcome == 'failure' }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: "11"
          cache: gradle

      - name: Retry build on Java 11 (attempt 2)
        id: build_j11
        if: ${{ steps.build_j17.outcome == 'failure' }}
        run: |
          ./gradlew clean --no-daemon
          ./gradlew $MODULE:assemble$BUILD_TYPE \
            -x lint -x lintVitalRelease -x test \
            --refresh-dependencies --no-daemon --stacktrace --info --warning-mode all $GRADLE_ARGS

      - name: Fail if both attempts failed
        if: ${{ steps.build_j17.outcome == 'failure' && steps.build_j11.outcome == 'failure' }}
        run: |
          echo "Build failed on both JDK 17 and JDK 11." >&2
          exit 1

      - name: Upload build artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ env.BUILD_TYPE }}
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
          if-no-files-found: ignore
