name: Build Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y             build-essential git zip unzip openjdk-17-jdk             python3-pip python3-setuptools python3-wheel python3-dev             libffi-dev libssl-dev libsqlite3-dev zlib1g-dev             libjpeg-dev libpng-dev libgl1-mesa-dev libgles2-mesa-dev libegl1             libmtdev-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev             xclip xsel libusb-1.0-0-dev libudev-dev pkg-config cmake

      - name: Install buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.36 virtualenv

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "[app]" > buildozer.spec
            echo "title = MyApp" >> buildozer.spec
            echo "package.name = myapp" >> buildozer.spec
            echo "package.domain = org.example" >> buildozer.spec
            echo "source.dir = ." >> buildozer.spec
            echo "version = 1.0.0" >> buildozer.spec
            echo "" >> buildozer.spec
            echo "[buildozer]" >> buildozer.spec
            echo "log_level = 2" >> buildozer.spec
          fi

      - name: Build APK (debug)
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: bin/*.apk
