name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install buildozer

      - name: Build APK
        run: |
          cd your_project_directory
          buildozer android update
          yes | buildozer android prepare
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: your_project_directory/bin/*.apk
