name: Build Signed APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      ANDROID_HOME: ${{ github.workspace }}/Android/Sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/Android/Sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            ${{ github.workspace }}/Android
          key: android-sdk-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git zip unzip openjdk-17-jdk wget

      - name: Download Android Command Line Tools
        run: |
          mkdir -p ${{ github.workspace }}/Android/cmdline-tools
          cd ${{ github.workspace }}/Android/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mkdir -p latest
          mv cmdline-tools/* latest/
          rm -rf cmdline-tools commandlinetools-linux-9477386_latest.zip
          echo "${{ github.workspace }}/Android/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install SDK Packages
        run: |
          yes | sdkmanager --sdk_root=${{ github.workspace }}/Android/Sdk --licenses
          sdkmanager --sdk_root=${{ github.workspace }}/Android/Sdk             "platform-tools"             "platforms;android-30"             "build-tools;30.0.3"
          echo "${{ github.workspace }}/Android/Sdk/platform-tools" >> $GITHUB_PATH
          echo "${{ github.workspace }}/Android/Sdk/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build Release APK
        run: |
          buildozer android release

      - name: Decode Keystore
        run: |
          if [ -n "${{ secrets.KEYSTORE_FILE }}" ]; then echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > my-release-key.keystore; fi
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      - name: Sign APK
        if: ${{ env.HAVE_KEY }}
        env:
          HAVE_KEY: ${{ secrets.KEYSTORE_FILE != '' && secrets.KEYSTORE_PASSWORD != '' && secrets.KEY_PASSWORD != '' && secrets.KEY_ALIAS != '' }}
        run: |
          if [ "$HAVE_KEY" = "true" ]; then             jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256             -keystore my-release-key.keystore             -storepass ${{ secrets.KEYSTORE_PASSWORD }}             -keypass ${{ secrets.KEY_PASSWORD }}             bin/*.apk ${{ secrets.KEY_ALIAS }};           else             echo "No signing secrets provided. Skipping signing.";           fi

      - name: Align APK
        run: |
          if compgen -G "bin/*.apk" > /dev/null; then             zipalign -v 4 bin/*.apk app-release.apk;           else             echo "No APK found in bin/. Build may have failed";             exit 1;           fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app-release.apk
