name: Build Android APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools python3-wheel python3-dev \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev \
            libjpeg-dev libpng-dev libgl1-mesa-dev libgles2-mesa-dev libegl1 \
            libmtdev-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev \
            xclip xsel libusb-1.0-0-dev libudev-dev pkg-config cmake

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: bin/*.apk
